# ip_retrieval_url is used to determine your external IP
# if it isn't configured, we'll default to https://dynamicdns.park-your-domain.com/getip
ip_retrieval_url: "http://ipecho.net/plain"
# the domains key is required
domains:
  # some name for you to identify the domain
  arbitrary_name1:
    # to update the second level domain, e.g. "example.com", use "@"
    host: "@"
    domain: "example.com"
    password: "checknamecheapforyourpassword"
  arbitrary_name2:
    # if you want to update a subdomain, use that for host
    # this configuration would update "subdomain.example.com"
    host: "subdomain"
    domain: "example.com"
    password: "foobar"
